services:
  - type: web
    name: ai-fines-herbes-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-fines-herbes-backend.onrender.com
      - key: NEXT_PUBLIC_SITE_URL
        value: https://ai-fines-herbes-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: main 